#name: Build and deploy ASP.Net Core app to Azure Web App - wa-github-workflows

name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Setup EF Tools
        run: |
          dotnet tool install --global dotnet-ef 
          dotnet tool restore

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Build EF Bundle
        run: dotnet ef migrations bundle --project Web --output ./data/efbundle.exe --self-contained --force --

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Upload EF Migrations Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: efbundle
          path: ./data
  
  tests:
    runs-on: windows-latest
    needs: build
    permissions: write-all

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Run Tests from Artifact
        run: dotnet test Tests.dll --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults
        continue-on-error: false  # Don't allow the job to continue even if tests fail

      - name: Upload test results to the workflow run in a zip file
        uses: actions/upload-artifact@v4
        if: ${{ always() }} # Always run this step even if tests fail
        with:
          name: test-results
          path: "**/*.trx"

      - name: Add Dorny test results to the workflow run
        uses: dorny/test-reporter@v1
        if: always()  # Always run this step even if tests fail
        with:
          name: Test Results
          artifact: test-results
          path: "**/*.trx"  # Path to the TRX test result files created by 'dotnet test'
          reporter: dotnet-trx  # Use the .NET TRX parser
          fail-on-error: false  # Don't fail the workflow if the report has issues

  deploy:
    runs-on: windows-latest
    needs: tests
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Download EF artifact from build job (bundle & script)
        uses: actions/download-artifact@v4
        with:
          name: efbundle

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Run EF migrations from bundle
        run:
          ./efbundle.exe --connection "${{ secrets.AZURE_SQL_CONNECTIONSTRING }}"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wa-github-workflows'
          slot-name: 'Production'
          package: .
